<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { RefreshCw, Save, Send, Stethoscope } from '@lucide/vue'
import { api } from '../services/http'
import SectionHeader from './SectionHeader.vue'
const data=ref<any>({});const schedule=ref<any>({briefing_times:[]});const status=ref('');const failed=ref(false)
const form=reactive<any>({webhook_enabled:false,webhook_url:'',wechat_enabled:false,wechat_webhook:'',telegram_enabled:false,telegram_bot_token:'',telegram_chat_id:'',qq_enabled:false,qq_app_id:'',qq_client_secret:'',qq_openid:'',briefing_times:'08:00, 20:00'})
const channels=[{k:'webhook',n:'通用 Webhook',e:'webhook_enabled',fields:[['webhook_url','Webhook URL']]},{k:'wechat',n:'企业微信',e:'wechat_enabled',fields:[['wechat_webhook','Webhook URL']]},{k:'telegram',n:'Telegram',e:'telegram_enabled',fields:[['telegram_bot_token','Bot Token（留空不改）'],['telegram_chat_id','Chat ID']]},{k:'qq',n:'QQ Bot',e:'qq_enabled',fields:[['qq_app_id','App ID'],['qq_client_secret','Client Secret（留空不改）'],['qq_openid','OpenID']]}]
function note(t:string,e=false){status.value=t;failed.value=e;setTimeout(()=>status.value='',4500)}
async function load(){try{const[d,s]:any=await Promise.all([api('/api/v1/admin/notifications'),api('/api/v1/admin/notifications/schedule')]);data.value=d;schedule.value=s;Object.assign(form,{webhook_enabled:d.webhook.enabled,webhook_url:d.webhook.url,wechat_enabled:d.wechat.enabled,wechat_webhook:d.wechat.webhook,telegram_enabled:d.telegram.enabled,telegram_chat_id:d.telegram.chat_id,qq_enabled:d.qq.enabled,qq_app_id:d.qq.app_id,qq_openid:d.qq.openid,briefing_times:(s.briefing_times||[]).join(', ')})}catch(e:any){note(e.message,true)}}
async function save(){try{const payload:any={...form};delete payload.briefing_times;for(const k of ['telegram_bot_token','qq_client_secret'])if(!payload[k])delete payload[k];await api('/api/v1/admin/notifications',{method:'PUT',body:JSON.stringify(payload)});await api('/api/v1/admin/notifications/schedule',{method:'PUT',body:JSON.stringify({briefing_times:form.briefing_times.split(',').map((x:string)=>x.trim()).filter(Boolean)})});note('通知配置与简报时间已保存');await load()}catch(e:any){note(e.message,true)}}
async function toggle(key:string,enabled:boolean){try{await api(`/api/v1/admin/channels/${key}/toggle`,{method:'PUT',body:JSON.stringify({enabled})});note('频道状态已更新');await load()}catch(e:any){note(e.message,true)}}
async function diagnose(channel:string){try{const d:any=await api('/api/v1/admin/notifications/diagnose',{method:'POST',body:JSON.stringify({channel})});note(d.result?.detail||`${channel} 诊断完成`)}catch(e:any){note(e.message,true)}}
async function sendTest(channel:string){const phrase=`SEND TEST ${channel.toUpperCase()}`;if(prompt(`输入确认短语：${phrase}`)!==phrase)return;try{const d:any=await api('/api/v1/admin/notifications/test',{method:'POST',body:JSON.stringify({channel,confirmation:phrase})});note(d.result?.detail||`${channel} 测试已发送`)}catch(e:any){note(e.message,true)}}
onMounted(load)
</script>
<template><div class="space-y-4"><div v-if="status" class="panel border-l-4 p-3 text-xs" :class="failed?'text-loss':'text-profit'">{{status}}</div><section class="panel p-4 sm:p-5"><SectionHeader title="通知频道中心" subtitle="QQ、企业微信、Telegram 与 Webhook"><template #actions><div class="flex gap-2"><button class="btn" @click="load"><RefreshCw :size="14"/></button><button class="btn btn-primary" @click="save"><Save :size="14"/>保存全部</button></div></template></SectionHeader><div class="grid gap-3 xl:grid-cols-2"><article v-for="c in channels" :key="c.k" class="subpanel key-card p-4" :class="form[c.e]?'key-card-profit':'key-card-brand'"><div class="flex items-center justify-between"><b>{{c.n}}</b><label class="data-pill" :class="form[c.e]?'data-pill-profit':''"><input v-model="form[c.e]" type="checkbox"/>{{form[c.e]?'已启用':'已关闭'}}</label></div><div class="mt-3 space-y-2"><div v-for="f in c.fields" :key="String(f[0])"><label class="label">{{f[1]}}</label><input v-model="form[f[0]]" class="input" :type="String(f[0]).includes('token')||String(f[0]).includes('secret')?'password':'text'"/></div></div><div class="mt-3 flex flex-wrap gap-2"><button class="btn" @click="diagnose(c.k)"><Stethoscope :size="13"/>诊断</button><button class="btn" @click="sendTest(c.k)"><Send :size="13"/>测试</button><button class="btn" @click="toggle(c.k,!form[c.e])">{{form[c.e]?'关闭':'启用'}}</button></div></article></div></section><section class="panel p-4"><SectionHeader title="定时简报" :subtitle="schedule.event_notifications"/><label class="label">发送时间（逗号分隔，24小时 HH:MM）</label><input v-model="form.briefing_times" class="input" placeholder="08:00, 20:00"/><p class="mt-2 text-[10px] muted">自进化 {{schedule.self_improvement_time||'20:00'}} · 灾备 {{schedule.backup_time||'02:00'}} · 时区 Asia/Shanghai</p></section></div></template>
