<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { KeyRound, LockOpen, Plus, RefreshCw, UserCog } from '@lucide/vue'
import { api } from '../services/http'
import SectionHeader from './SectionHeader.vue'
import EmptyState from './EmptyState.vue'
const props=defineProps<{currentUser:any}>()
const users=ref<any[]>([]);const busy=ref(false);const status=ref('');const failed=ref(false)
const create=reactive({username:'',password:'',role:'admin'});const password=reactive({current_password:'',new_password:''})
function note(text:string,error=false){status.value=text;failed.value=error;setTimeout(()=>status.value='',4000)}
async function load(){busy.value=true;try{const d:any=await api('/api/v1/admin/users');users.value=d.users||[]}catch(e:any){note(e.message,true)}finally{busy.value=false}}
async function createUser(){try{await api('/api/v1/admin/users',{method:'POST',body:JSON.stringify(create)});create.username='';create.password='';note('管理员已创建');await load()}catch(e:any){note(e.message,true)}}
async function toggle(user:any){try{await api(`/api/v1/admin/users/${user.id}/enabled`,{method:'PUT',body:JSON.stringify({enabled:!user.enabled})});note('账号状态已更新');await load()}catch(e:any){note(e.message,true)}}
async function unlock(user:any){const phrase=`UNLOCK ADMIN ${user.id}`;if(prompt(`输入确认短语：${phrase}`)!==phrase)return;try{await api(`/api/v1/admin/users/${user.id}/unlock`,{method:'POST',body:JSON.stringify({confirmation:phrase})});note('账号已解锁');await load()}catch(e:any){note(e.message,true)}}
async function resetPassword(user:any){const next=prompt(`为 ${user.username} 设置新密码（至少12位，包含字母和数字）`);if(!next)return;try{await api(`/api/v1/admin/users/${user.id}/password`,{method:'PUT',body:JSON.stringify({current_password:'',new_password:next})});note('管理员密码已重置');await load()}catch(e:any){note(e.message,true)}}
async function changePassword(){try{await api(`/api/v1/admin/users/${props.currentUser.id}/password`,{method:'PUT',body:JSON.stringify(password)});password.current_password='';password.new_password='';note('密码修改成功，请重新登录')}catch(e:any){note(e.message,true)}}
onMounted(load)
</script>
<template><div class="space-y-4"><div v-if="status" class="panel border-l-4 p-3 text-xs" :class="failed?'text-loss':'text-profit'">{{status}}</div><section class="panel p-4 sm:p-5"><SectionHeader title="管理员账号" subtitle="创建、停用、解锁和角色管理" :count="users.length"><template #actions><button class="btn" @click="load"><RefreshCw :size="14"/>刷新</button></template></SectionHeader><div v-if="users.length" class="grid gap-2.5 lg:grid-cols-2"><article v-for="u in users" :key="u.id" class="subpanel key-card p-4" :class="u.enabled?'key-card-profit':'key-card-loss'"><div class="flex items-start justify-between gap-3"><div><div class="flex items-center gap-2"><b>{{u.username}}</b><span class="badge">{{u.role}}</span><span v-if="u.id===currentUser.id" class="badge badge-profit">当前账号</span></div><p class="mt-2 text-[10px] muted">最后登录 {{u.last_login_at||'从未登录'}} · ID {{u.id}}</p></div><span class="badge" :class="u.enabled?'badge-profit':'badge-loss'">{{u.enabled?'已启用':'已停用'}}</span></div><div class="mt-4 flex flex-wrap gap-2 border-t divider pt-3"><button v-if="u.id!==currentUser.id" class="btn" :class="u.enabled?'btn-danger':''" @click="toggle(u)">{{u.enabled?'停用账号':'启用账号'}}</button><button class="btn" @click="unlock(u)"><LockOpen :size="14"/>解除锁定</button><button v-if="u.id!==currentUser.id" class="btn" @click="resetPassword(u)"><KeyRound :size="14"/>重置密码</button></div></article></div><EmptyState v-else text="暂无管理员账号"/></section><div class="grid gap-4 xl:grid-cols-2"><section class="panel p-4 sm:p-5"><SectionHeader title="创建管理员" subtitle="仅超级管理员可执行"/><div class="grid gap-3 sm:grid-cols-2"><div><label class="label">账号</label><input v-model="create.username" class="input" placeholder="operator"/></div><div><label class="label">角色</label><select v-model="create.role" class="input"><option value="admin">管理员</option><option value="superadmin">超级管理员</option></select></div><div class="sm:col-span-2"><label class="label">初始密码</label><input v-model="create.password" class="input" type="password" placeholder="至少12位，包含字母和数字"/></div></div><button class="btn btn-primary mt-4" @click="createUser"><Plus :size="14"/>创建账号</button></section><section class="panel p-4 sm:p-5"><SectionHeader title="修改当前密码" subtitle="修改成功后需要重新登录"/><label class="label">当前密码</label><input v-model="password.current_password" class="input mb-3" type="password"/><label class="label">新密码</label><input v-model="password.new_password" class="input" type="password" placeholder="至少12位，包含字母和数字"/><button class="btn mt-4" @click="changePassword"><KeyRound :size="14"/>修改密码</button></section></div></div></template>
