<script setup lang="ts">
import { ref } from 'vue'
import { X, Copy, BrainCircuit } from '@lucide/vue'
import SectionHeader from '../components/SectionHeader.vue'
import EmptyState from '../components/EmptyState.vue'
import { useTerminalStore } from '../stores/terminal'
const store=useTerminalStore(); const selected=ref<any>(null); const showPrompt=ref(false)
const factors=()=>store.data.factors||[]
const tone=(a:string)=>a==='BUY_LONG'?'badge-profit':a==='SELL_SHORT'?'badge-loss':'badge'
async function copyPrompt(){ await navigator.clipboard?.writeText(store.data.ai_last_prompt||'') }
</script>
<template><div class="space-y-4">
  <section class="panel p-4 sm:p-5"><SectionHeader title="AI 大脑实时决策与全维因子矩阵" subtitle="多周期趋势、量化因子、概率与聪明钱共振" :count="factors().length"><template #actions><button class="btn" @click="showPrompt=true"><BrainCircuit :size="15"/>实时提示词</button></template></SectionHeader>
    <div v-if="factors().length" class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><button v-for="f in factors()" :key="f.instId||f.name" class="panel panel-hover key-card p-4 text-left" :class="f.action==='BUY_LONG'?'key-card-profit':f.action==='SELL_SHORT'?'key-card-loss':'key-card-brand'" @click="selected=f"><div class="flex items-start justify-between"><div><b class="font-mono text-base">{{ f.name||f.instId }}</b><p class="mt-1 text-xs muted">{{ f.instId }}</p></div><span :class="tone(f.action)" class="badge">{{ f.action||'WAIT' }}</span></div><div class="mt-4 grid grid-cols-3 gap-2 text-xs font-mono"><div class="subpanel p-2"><span class="muted text-[9px]">现价</span><b class="key-number mt-1 block text-brand">{{ f.price||'--' }}</b></div><div class="subpanel p-2"><span class="muted text-[9px]">24H</span><b class="key-number mt-1 block" :class="Number(f.chg24h||f.change24h)>=0?'text-profit':'text-loss'">{{ Number(f.chg24h||f.change24h||0)>=0?'+':'' }}{{ f.chg24h||f.change24h||0 }}%</b></div><div class="subpanel p-2"><span class="muted text-[9px]">置信度</span><b class="key-number mt-1 block text-brand">{{ f.confidence||'--' }}%</b></div></div><p class="mt-3 line-clamp-2 text-[11px] leading-relaxed muted">{{ f.reason||'等待下一轮 AI 推演结果' }}</p></button></div><EmptyState v-else text="暂无 AI 大脑决策数据"/>
  </section>
  <section class="panel p-4 sm:p-5"><SectionHeader title="AI 大脑历史决策推演审计流" subtitle="保留宏观判断和持仓管理指令" :count="(store.data.ai_brain_history||[]).length"/>
    <div v-if="(store.data.ai_brain_history||[]).length" class="space-y-3"><article v-for="(h,i) in store.data.ai_brain_history" :key="i" class="subpanel p-4"><div class="flex justify-between text-[10px] font-mono"><span class="data-pill data-pill-brand"><b>{{ h.time||'--' }}</b></span><span class="muted">LLM 推演周期</span></div><p class="mt-2 text-sm leading-relaxed">{{ h.macro_assessment||'宏观中性震荡' }}</p></article></div><EmptyState v-else text="暂无历史决策记录"/>
  </section>
  <div v-if="selected" class="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur" @click.self="selected=null"><div class="panel max-h-[85vh] w-full max-w-2xl overflow-auto p-5" role="dialog"><div class="flex items-center justify-between"><div><h3 class="font-mono text-lg font-black">{{ selected.name||selected.instId }}</h3><p class="muted text-xs">AI 决策因子详情</p></div><button class="btn !px-2" @click="selected=null"><X :size="16"/></button></div><div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div v-for="(v,k) in {动作:selected.action||'WAIT',现价:selected.price||'--',置信度:`${selected.confidence||'--'}%`,杠杆:`${selected.leverage||3}x`}" :key="k" class="subpanel p-3"><span class="muted text-[10px]">{{ k }}</span><b class="mt-1 block font-mono">{{ v }}</b></div></div><div class="subpanel mt-3 p-4"><span class="muted text-[10px]">核心决策逻辑</span><p class="mt-2 text-sm leading-7">{{ selected.reason||selected.desc||'暂无详细说明' }}</p></div></div></div>
  <div v-if="showPrompt" class="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur" @click.self="showPrompt=false"><div class="panel flex max-h-[88vh] w-full max-w-5xl flex-col p-5"><div class="flex items-center justify-between"><div><h3 class="font-mono text-base font-black">实时 AI 大脑提示词</h3><p class="muted text-xs">System + User Prompt 快照</p></div><div class="flex gap-2"><button class="btn" @click="copyPrompt"><Copy :size="14"/>复制</button><button class="btn !px-2" @click="showPrompt=false"><X :size="16"/></button></div></div><pre class="subpanel mt-4 overflow-auto whitespace-pre-wrap p-4 text-[11px] leading-6">{{ store.data.ai_last_prompt||'暂无提示词快照' }}</pre></div></div>
</div></template>
